import { expect, test } from '@playwright/test';

test('unified static feed, full details, publication policy and Pages discovery', async ({ page }, info) => {
  await page.goto('/pages/');
  await page.getByRole('link', { name: '~/blog/pages/memos.md', exact: true }).click();
  await expect(page).toHaveURL(/\/pages\/memos\/$/u);
  await expect(page.getByRole('heading', { name: 'Memos', exact: true })).toBeVisible();
  await expect(page.locator('[data-memo-entry]')).toHaveCount(20);
  await expect(page.locator('#m_fixture_recent .memo-body')).toContainText('An intentional second line.');
  await expect(page.locator('#m_fixture_recent br')).toHaveCount(1);
  await expect(page.locator('[data-content-marker="featured"]')).toHaveText('Featured');
  await expect(page.locator('#m_fixture_recent .memo-tags')).toHaveText('#reading');
  await expect(page.locator('form,input,textarea,[data-document-navigator]')).toHaveCount(0);
  await expect(page.locator('#m_fixture_draft,#m_fixture_private')).toHaveCount(0);
  expect((await page.request.get('/pages/memos/m_fixture_draft/')).status()).toBe(404);
  expect((await page.request.get('/pages/memos/assets/orphan.png')).status()).toBe(404);
  await page.screenshot({ path: info.outputPath('integrated-memo-reading.png') });
  const preview = page.locator('#m_fixture_middle');
  await expect(preview).not.toContainText('The final line survives in full.');
  await preview.getByRole('link', { name: /Read full entry/u }).click();
  await expect(page).toHaveURL(/\/pages\/memos\/m_fixture_middle\/$/u);
  await expect(page.getByRole('heading', { name: 'A longer note', exact: true })).toBeVisible();
  await expect(page.locator('.memo-body')).toContainText('The final line survives in full.');
  await expect(page.locator('pre code').filter({ hasText: 'code indentation' })).toContainText('  code indentation');
  await expect(page.getByAltText('Synthetic pixel')).toBeVisible();
  await expect(page.locator('.memo-body script')).toHaveCount(0);
  expect((await page.request.get('/pages/memos/assets/pixel.png')).status()).toBe(200);
  expect((await page.request.get('/pages/memos/assets/%E5%9B%BE%E5%83%8F.png')).status()).toBe(200);
  await expect(page.getByAltText('Encoded Unicode image')).toBeVisible();
  await page.screenshot({ path: info.outputPath('integrated-memo-detail.png') });
  await page.getByRole('link', { name: /Return to timeline/u }).first().click();
  await expect(page).toHaveURL(/\/pages\/memos\/#m_fixture_middle$/u);
  await expect(page.locator('#m_fixture_middle')).toBeVisible();
});

test('empty/single timelines, keyboard links, zoom and local overflow stay readable', async ({ page }, info) => {
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('/pages/memos/m_fixture_middle/');
  await page.keyboard.press('Tab');
  await expect(page.getByRole('link', { name: 'Skip to content' })).toBeFocused();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.evaluate(() => { document.documentElement.style.fontSize = '200%'; });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await expect(page.locator('pre code').filter({ hasText: 'code indentation' })).toContainText('code indentation');
  await page.screenshot({ path: info.outputPath('integrated-memo-zoom.png') });
  await page.goto('/fixture-empty/pages/memos/');
  await expect(page.locator('.memo-empty')).toHaveText('No Memo entries have been published yet.');
  await expect(page.getByRole('slider', { name: 'Historical time' })).toBeHidden();
  await page.goto('/fixture-single/pages/memos/');
  await expect(page.locator('[data-memo-entry]')).toHaveCount(1);
  await expect(page.getByRole('slider', { name: 'Historical time', includeHidden: true })).toHaveAttribute('aria-disabled', 'true');
});

test('scrub, natural scroll, equal months and detail return synchronize in both orientations', async ({ page }, info) => {
  test.skip(!info.project.use.javaScriptEnabled, 'Static time navigation uses month links.');
  await page.goto('/pages/memos/');
  const root = page.locator('[data-memo-timeline]');
  const slider = page.getByRole('slider', { name: 'Historical time' });
  await expect(root).toHaveAttribute('data-memo-ready', 'true');
  const horizontal = info.project.name.includes('mobile');
  await expect(slider).toHaveAttribute('aria-orientation', horizontal ? 'horizontal' : 'vertical');
  const intervals = await page.locator('[data-memo-month-tick]').evaluateAll((ticks) => ticks.map((tick) => Number((tick as HTMLElement).dataset.memoSegmentEnd) - Number((tick as HTMLElement).dataset.memoSegmentStart)));
  expect(intervals).toEqual([.25, .25, .25, .25]);
  const historyBefore = await page.evaluate(() => history.length);
  await slider.focus();
  await page.keyboard.press('PageDown');
  await expect(root).toHaveAttribute('data-memo-active-id', 'm_fixture_middle');
  await expect(root).toHaveAttribute('data-memo-interaction', 'browsing');
  await expect(slider).toHaveAttribute('aria-valuetext', '2024-08-04 18:20');
  await page.waitForTimeout(150);
  await expect(root).toHaveAttribute('data-memo-active-id', 'm_fixture_middle');
  await page.keyboard.press('End');
  await expect(root).toHaveAttribute('data-memo-active-id', 'm_fixture_oldest');
  await expect.poll(() => page.locator('#m_fixture_oldest').evaluate((entry) => {
    const header = document.querySelector('[data-memo-header]')!.getBoundingClientRect();
    const rail = document.querySelector('[data-memo-time-control]')!.getBoundingClientRect();
    const clearance = matchMedia('(max-width:48rem)').matches ? rail.bottom : header.bottom;
    return entry.getBoundingClientRect().top >= clearance - 1;
  })).toBe(true);
  await page.keyboard.press('Home');
  await expect(root).toHaveAttribute('data-memo-active-id', 'm_fixture_recent');
  const box = await slider.boundingBox();
  expect(box).not.toBeNull();
  const coordinate = (fraction: number) => ({ x: box!.x + box!.width * (horizontal ? fraction : .85), y: box!.y + box!.height * (horizontal ? .5 : fraction) });
  const start = coordinate(.02);
  const end = coordinate(.65);
  await page.mouse.move(start.x, start.y);
  await page.mouse.down();
  await page.mouse.move(end.x, end.y, { steps: 6 });
  await expect(root).toHaveAttribute('data-memo-interaction', 'dragging');
  await page.mouse.up();
  await expect(root).toHaveAttribute('data-memo-interaction', 'browsing');
  await expect(root).toHaveAttribute('data-memo-active-id', 'm_fixture_old');
  await expect(slider).toHaveAttribute('aria-valuetext', '2022-03-21 19:59');
  expect(await page.evaluate(() => history.length)).toBe(historyBefore);
  await page.evaluate(() => scrollTo({ top: 0, behavior: 'instant' }));
  await expect(root).toHaveAttribute('data-memo-active-id', 'm_fixture_recent');
  await page.locator('#m_fixture_middle').scrollIntoViewIfNeeded();
  await page.evaluate(() => {
    const card = document.querySelector('#m_fixture_middle')!;
    const header = document.querySelector('[data-memo-header]')!.getBoundingClientRect().bottom;
    const offset = matchMedia('(max-width:48rem)').matches ? header + document.querySelector('[data-memo-time-control]')!.getBoundingClientRect().height : header;
    scrollTo({ top: scrollY + card.getBoundingClientRect().top - offset - 20, behavior: 'instant' });
  });
  await expect(root).toHaveAttribute('data-memo-active-id', 'm_fixture_middle');
  await page.locator('#m_fixture_middle .memo-date').click();
  await expect(page).toHaveURL(/\/m_fixture_middle\/$/u);
  await page.goBack();
  await expect(root).toHaveAttribute('data-memo-active-id', 'm_fixture_middle');
  await page.goto('/pages/memos/#m_fixture_old');
  await expect(root).toHaveAttribute('data-memo-active-id', 'm_fixture_old');
  await page.setViewportSize({ width: horizontal ? 900 : 375, height: 812 });
  await expect(slider).toHaveAttribute('aria-orientation', horizontal ? 'vertical' : 'horizontal');
  await expect(root).toHaveAttribute('data-memo-active-id', 'm_fixture_old');
});

test('missing controller keeps native month/detail navigation', async ({ page }, info) => {
  test.skip(!info.project.use.javaScriptEnabled, 'Static reading covers unavailable JavaScript.');
  await page.route('**/MemoTimeline*.js', (route) => route.abort());
  await page.goto('/pages/memos/');
  await expect(page.getByRole('slider', { name: 'Historical time' })).toBeHidden();
  await page.getByText('Browse months', { exact: true }).click();
  await page.getByRole('link', { name: '2022-03', exact: true }).click();
  await expect(page).toHaveURL(/#m_fixture_old$/u);
  await expect(page.locator('#m_fixture_old')).toBeVisible();
  await page.locator('#m_fixture_old .memo-date').click();
  await expect(page).toHaveURL(/\/m_fixture_old\/$/u);
});

test('mobile touch scrubs the rail while content keeps native vertical scrolling', async ({ page }, info) => {
  test.skip(info.project.name !== 'memos-mobile-interactive', 'Touch gestures use the maintained mobile interactive project.');
  await page.goto('/pages/memos/');
  const root = page.locator('[data-memo-timeline]');
  await expect(root).toHaveAttribute('data-memo-ready', 'true');
  const box = await page.getByRole('slider', { name: 'Historical time' }).boundingBox();
  expect(box).not.toBeNull();
  const session = await page.context().newCDPSession(page);
  const touch = (x: number, y: number) => [{ x, y, id: 1 }];
  await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: touch(box!.x + box!.width * .05, box!.y + box!.height * .5) });
  await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: touch(box!.x + box!.width * .65, box!.y + box!.height * .5) });
  await expect(root).toHaveAttribute('data-memo-interaction', 'dragging');
  await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  await expect(root).toHaveAttribute('data-memo-active-id', 'm_fixture_old');
  await expect(root).toHaveAttribute('data-memo-interaction', 'browsing');
  await page.goto('/pages/memos/');
  await expect(root).toHaveAttribute('data-memo-active-id', 'm_fixture_recent');
  const before = await page.evaluate(() => scrollY);
  await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: touch(190, 650) });
  for (let y = 600; y >= 350; y -= 50) await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: touch(190, y) });
  await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  await expect.poll(() => page.evaluate(() => scrollY)).toBeGreaterThan(before + 100);
  await expect(root).toHaveAttribute('data-memo-interaction', 'browsing');
  await session.detach();
});

test('month disclosure is touch-sized and native month navigation stays available', async ({ page }) => {
  await page.goto('/pages/memos/');
  const disclosure = page.getByText('Browse months', { exact: true });
  expect((await disclosure.boundingBox())!.height).toBeGreaterThanOrEqual(44);
  await disclosure.click();
  const month = page.getByRole('link', { name: '2022-03', exact: true });
  expect((await month.boundingBox())!.height).toBeGreaterThanOrEqual(44);
  await month.click();
  await expect(page).toHaveURL(/#m_fixture_old$/u);
  await expect(page.locator('#m_fixture_old')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
