import { expect, test } from '@playwright/test';

const writeOrigin = 'https://site.fixture.invalid';

test('native memo navigation, escaped text and exact URL-encoded consent submission', async ({ page }, testInfo) => {
  await page.goto('/');
  const memoLink = page.locator('[data-terminal-fallback] a[href="/memos/"]:visible');
  await expect(memoLink).toBeVisible();
  await expect(memoLink).not.toHaveAttribute('data-home-browse-directory');
  await memoLink.click();
  await expect(page).toHaveURL(/\/memos\/$/u);
  await expect(page.locator('.memo-list h3').first()).toHaveText('<b>Reader 😀</b>');
  await expect(page.locator('.memo-body').first()).toContainText('<script>memoHostile()</script> & plain text\nSecond line 😀');
  await expect(page.locator('.memo-list script, .memo-list b')).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(await page.locator('.memo-body').first().evaluate((node) => getComputedStyle(node).whiteSpace)).toBe('pre-wrap');
  await page.screenshot({ path: testInfo.outputPath('memos-page.png'), fullPage: true });
  const consent = page.getByLabel('I agree to publish');
  await expect(consent).not.toBeChecked();
  await expect(consent).toHaveAttribute('required', '');
  await expect(page.getByLabel('Display name', { exact: true })).not.toHaveAttribute('maxlength');
  await page.getByLabel('Display name', { exact: true }).fill('😀'.repeat(80));
  await page.getByLabel('Private verification email').fill('reader@example.invalid');
  const body = 'Native + & = 😀\nA second line.';
  await page.getByLabel('Your note (plain text)').fill(body);
  let requests = 0;
  await page.route(`${writeOrigin}/v1/memos/submissions`, async (route) => {
    requests += 1;
    const request = route.request();
    expect(request.method()).toBe('POST');
    expect(request.headers()['content-type']).toContain('application/x-www-form-urlencoded');
    const fields = new URLSearchParams(request.postData() ?? '');
    expect([...fields.keys()].sort()).toEqual(['body', 'consent', 'consentVersion', 'displayName', 'email', 'honeypot']);
    expect(fields.get('displayName')).toBe('😀'.repeat(80));
    expect(fields.get('body')).toBe(body.replaceAll('\n', '\r\n'));
    expect(fields.get('email')).toBe('reader@example.invalid');
    expect(fields.get('consent')).toBe('accepted');
    expect(fields.get('consentVersion')).toBe('memo-fixture-v1');
    expect(fields.get('honeypot')).toBe('');
    await route.fulfill({ status: requests === 1 ? 202 : 400, contentType: 'text/html', body: `<!doctype html><html lang="en"><meta name="viewport" content="width=device-width"><title>Firefly memos</title><main><h1>Firefly memos</h1><p>${requests === 1 ? 'If your submission is accepted, a verification email will arrive. It remains private until verification and owner approval.' : 'Please check the submitted fields.'}</p><a href="/memos/">Return to memos</a></main></html>` });
  });
  await page.getByRole('button', { name: 'Send verification email' }).click();
  expect(requests).toBe(0);
  await expect(page).toHaveURL(/\/memos\/$/u);
  await consent.check();
  await page.getByRole('button', { name: 'Send verification email' }).click();
  await expect(page.getByText('If your submission is accepted', { exact: false })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Return to memos' })).toHaveAttribute('href', '/memos/');
  await page.screenshot({ path: testInfo.outputPath('memos-accepted.png'), fullPage: true });
  const html = await (await page.request.get('/memos/')).text();
  await page.route(`${writeOrigin}/memos/`, (route) => route.fulfill({ contentType: 'text/html', body: html }));
  await page.getByRole('link', { name: 'Return to memos' }).click();
  await page.getByLabel('Display name', { exact: true }).fill('😀'.repeat(80));
  await page.getByLabel('Private verification email').fill('reader@example.invalid');
  await page.getByLabel('Your note (plain text)').fill(body);
  await page.getByLabel('I agree to publish').check();
  await page.getByRole('button', { name: 'Send verification email' }).click();
  await expect(page.getByText('Please check the submitted fields.')).toBeVisible();
  expect(requests).toBe(2);
});
